language: go

notificaitons:
  email:
    recipients: bluesuncorp01@gmail.com
    on_success: change
    on_failure: always

go:
  - 1.3
  - 1.4
  - tip

script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go test -v -covermode=count -coverprofile=cover.out

after_success:
  - goveralls -coverprofile=cover.out -service=travis-ci -repotoken I6M8FiXZzErImgwMotJ7fwFlHOX8Hqdq1