stopwatch:
  build: ./
  ports:
    - "4000:4000"
  links:
    - redis
    - vault
  volumes:
    - ..:/opt/stopwatch
redis:
  image: bjorn248/redis
  volumes:
    - ./data/redis:/data/redis
vault:
  image: bjorn248/vault
  cap_add:
    - IPC_LOCK
  volumes:
    - ./data/vault:/data/vault
